-- Order time window and totals fields
ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS setup_start TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS order_start TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS order_end TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS cleanup_end TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS calculated_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rebate_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_ex_vat NUMERIC(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS captured_rebate_percent NUMERIC(5,2) NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(16) NOT NULL DEFAULT 'Draft';

